// Generated by gencpp from file turn_msg/TurnResponse.msg
// DO NOT EDIT!


#ifndef TURN_MSG_MESSAGE_TURNRESPONSE_H
#define TURN_MSG_MESSAGE_TURNRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turn_msg
{
template <class ContainerAllocator>
struct TurnResponse_
{
  typedef TurnResponse_<ContainerAllocator> Type;

  TurnResponse_()
    : r1()
    , r2()
    , r3()  {
    }
  TurnResponse_(const ContainerAllocator& _alloc)
    : r1(_alloc)
    , r2(_alloc)
    , r3(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _r1_type;
  _r1_type r1;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _r2_type;
  _r2_type r2;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _r3_type;
  _r3_type r3;





  typedef boost::shared_ptr< ::turn_msg::TurnResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turn_msg::TurnResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurnResponse_

typedef ::turn_msg::TurnResponse_<std::allocator<void> > TurnResponse;

typedef boost::shared_ptr< ::turn_msg::TurnResponse > TurnResponsePtr;
typedef boost::shared_ptr< ::turn_msg::TurnResponse const> TurnResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turn_msg::TurnResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turn_msg::TurnResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turn_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turn_msg::TurnResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turn_msg::TurnResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turn_msg::TurnResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turn_msg::TurnResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turn_msg::TurnResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turn_msg::TurnResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turn_msg::TurnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cf32a6ad698361ab7b30bf94888c1cf";
  }

  static const char* value(const ::turn_msg::TurnResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cf32a6ad698361aULL;
  static const uint64_t static_value2 = 0xb7b30bf94888c1cfULL;
};

template<class ContainerAllocator>
struct DataType< ::turn_msg::TurnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turn_msg/TurnResponse";
  }

  static const char* value(const ::turn_msg::TurnResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turn_msg::TurnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] r1\n\
string[] r2\n\
string[] r3\n\
";
  }

  static const char* value(const ::turn_msg::TurnResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turn_msg::TurnResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r1);
      stream.next(m.r2);
      stream.next(m.r3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turn_msg::TurnResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turn_msg::TurnResponse_<ContainerAllocator>& v)
  {
    s << indent << "r1[]" << std::endl;
    for (size_t i = 0; i < v.r1.size(); ++i)
    {
      s << indent << "  r1[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.r1[i]);
    }
    s << indent << "r2[]" << std::endl;
    for (size_t i = 0; i < v.r2.size(); ++i)
    {
      s << indent << "  r2[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.r2[i]);
    }
    s << indent << "r3[]" << std::endl;
    for (size_t i = 0; i < v.r3.size(); ++i)
    {
      s << indent << "  r3[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.r3[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURN_MSG_MESSAGE_TURNRESPONSE_H
